/*
Name : 8g.c
Author : Ishita Kar
Description:Write a separate program using signal system call to catch the following signals.
g. SIGPROF(using settimer system call)
Date: 20th Sep, 2025.
_______________________________________________________________________________
*/

#include<stdio.h>
#include<stdlib.h>
#include<signal.h>
#include<unistd.h>
#include<sys/time.h>
void sigprof_handler(int sig)
{
        printf("Caught SIGPROF . Timer expired\n");
        exit(1);
}

int main()
{
        struct itimerval timer;
        signal(SIGPROF,sigprof_handler);
        printf("Setting Alarm for 1 sec...\n");
        timer.it_value.tv_sec=1;
        timer.it_value.tv_usec=0;
        timer.it_interval.tv_sec = 0;
        timer.it_interval.tv_usec = 0;
        setitimer(ITIMER_PROF,&timer,NULL);

        while (1) {
        for (long i = 0; i < 100000000; i++);
        printf("Working...\n");
    }
       
        return 0;
}

/*____________________________________________________________________________
 OUTPUT

 Setting Alarm for 1 sec...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Working...
Caught SIGPROF . Timer expired
_______________________________________________________________________________
*/
